#include<reg51.h>
#include<stdio.h>

void comma();
void latitude();
void longitude();
char GPS[69],LAT[8],LONG[9];
unsigned int i,j=0,k,l,m;
char test[]={"$GPRMC"};

void delay(int msec)
{
  int n;
  for(n=0;n<msec;n++)
 {
   TH0=0X00;
   TL0=0X00;
   TR0=0X01;
   while(TF0==0);
   TR0=0X00;
   TF0=0X00;
  }
}

void serial(void) interrupt 4
{
  GPS[j++]=SBUF;
  if(j<7)
   if(GPS[j-1]!=test[j-1])
    j=0;
  if(j==68)
 {
   IE=0x00;
   comma();
   if(GPS[m]!='V')
   {
    latitude();
    longitude();
    if((LAT[0]=='9')&&(LAT[1]=='7')&&(LAT[2]=='0')&&(LAT[3]<='9')&&(LAT[3]>='7'))
     if((LONG[0]=='7')&&(LONG[1]=='6')&&(LONG[2]=='6')&&(LONG[3]=='7')&& ….(LONG[4]>='2')&&(LONG[4]<='4'))
    {
      SBUF='!';
      while(TI==0);
      TI=0;
      SBUF='K';
      while(TI==0);
      TI=0;
      SBUF='O';
      while(TI==0);
      TI=0;
      SBUF='T';
      while(TI==0);
      TI=0;
      SBUF='T';
      while(TI==0);
       TI=0;
	      SBUF='A';
       while(TI==0);
       TI=0;
	      SBUF='R';
       while(TI==0);
       TI=0;
	      SBUF='A';
       while(TI==0);
       TI=0;
	      SBUF='M';
       while(TI==0);
       TI=0;
	      SBUF='A';
       while(TI==0);
       TI=0;
	      SBUF='T';
       while(TI==0);
       TI=0;
	      SBUF='T';
       while(TI==0);
       TI=0;
	      SBUF='O';
       while(TI==0);
       TI=0;
	      SBUF='M';
       while(TI==0);
       TI=0;
	      SBUF=' ';
       while(TI==0);
       TI=0;
	      SBUF='B';
       while(TI==0);
       TI=0;
	      SBUF='U';
       while(TI==0);
       TI=0;
	      SBUF='S';
       while(TI==0);
       TI=0;
	      SBUF=' ';
       while(TI==0);
       TI=0;
	      SBUF='S';
       while(TI==0);
       TI=0;
	      SBUF='T';
       while(TI==0);
       TI=0;
	      SBUF='A';
       while(TI==0);
       TI=0;
	      SBUF='N';
       while(TI==0);
       TI=0;
	      SBUF='D';
       while(TI==0);
       TI=0;
	      SBUF='\r';
       while(TI==0);
       TI=0;
      }
    if((LAT[0]=='9')&&(LAT[1]=='7')&&(LAT[2]=='2')&&(LAT[3]>='4')&&(LAT[3]<='9'))
....if((LONG[0]=='7')&&(LONG[1]=='6')&&(LONG[2]=='7')&&(LONG[3]=='2')&&(LONG…[4]>='2')&&(LONG[4]<='8')&&(LONG[6]>='4')&&(LONG[6]<='7'))
    {
     SBUF='!';
     while(TI==0);
     TI=0;
	    SBUF='S';
     while(TI==0);
     TI=0;
	    SBUF='J';
     while(TI==0);
     TI=0;
	    SBUF='C';
     while(TI==0);
     TI=0;
	    SBUF='E';
     while(TI==0);
     TI=0;
	    SBUF='T';
     while(TI==0);
     TI=0;
	    SBUF=',';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='C';
     while(TI==0);
     TI=0;
	    SBUF='H';
     while(TI==0);
     TI=0;
	    SBUF='O';
     while(TI==0);
     TI=0;
	    SBUF='O';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='D';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='C';
     while(TI==0);
     TI=0;
	    SBUF='H';
     while(TI==0);
     TI=0;
	    SBUF='E';
     while(TI==0);
     TI=0;
	    SBUF='R';
     while(TI==0);
     TI=0;
	    SBUF='R';
     while(TI==0);
     TI=0;
	    SBUF='Y';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='B';
     while(TI==0);
     TI=0;
	    SBUF='U';
     while(TI==0);
     TI=0;
	    SBUF='S';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='S';
     while(TI==0);
     TI=0;
	    SBUF='T';
     while(TI==0);
     TI=0;
	    SBUF='O';
     while(TI==0);
     TI=0;
	    SBUF='P';
     while(TI==0);
     TI=0;
	    SBUF='\r';
     while(TI==0);
     TI=0;
    }
..if((LAT[0]=='9')&&(LAT[1]<='7')&&(LAT[1]>='6')&&((LAT[2]=='0')||(LAT[2]=='9'))&&(..(LAT[3]=='1')||(LAT[3]=='8')||(LAT[3]=='9')||(LAT[3]=='0')))  ...if((LONG[0]=='7')&&(LONG[1]=='6')&&(LONG[2]=='7')&&(LONG[3]=='2')&&(LONG[...4]>='4')&&(LONG[4]<='8'))
   {
     SBUF='!';
     while(TI==0);
     TI=0;
	    SBUF='B';
     while(TI==0);
     TI=0;
	    SBUF='H';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='R';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='G';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='M';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='B';
     while(TI==0);
     TI=0;
	    SBUF='U';
     while(TI==0);
     TI=0;
	    SBUF='S';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='S';
     while(TI==0);
     TI=0;
	    SBUF='T';
     while(TI==0);
     TI=0;
	    SBUF='O';
     while(TI==0);
     TI=0;
	    SBUF='P';
     while(TI==0);
     TI=0;
	    SBUF='\r';
     while(TI==0);
     TI=0;
    }
..if((LAT[0]=='9')&&(LAT[1]=='5')&&((LAT[2]=='9')||(LAT[2]=='8'))&&((LAT[3]=='7')||(L..AT[3]=='8')||(LAT[3]=='9')||(LAT[3]=='0')||(LAT[3]=='1')||(LAT[3]=='2'))) …if((LONG[0]=='7')&&(LONG[1]=='6')&&((LONG[2]=='5')||(LONG[2]=='6'))&&((LONG[…3]=='9')||(LONG[3]=='0'))&&(LONG[4]>='0')&&(LONG[4]<='9'))
    {
     SBUF='!';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='D';
     while(TI==0);
     TI=0;
	    SBUF='I';
     while(TI==0);
     TI=0;
	    SBUF='V';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='Y';
     while(TI==0);
     TI=0;
	    SBUF='A';
     while(TI==0);
     TI=0;
	    SBUF='L';
     while(TI==0);
     TI=0;
	    SBUF=' ';
     while(TI==0);
     TI=0;
	    SBUF='J';
     while(TI==0);
     TI=0;
	    SBUF='U';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	    SBUF='C';
     while(TI==0);
     TI=0;
	    SBUF='T';
     while(TI==0);
     TI=0;
	    SBUF='I';
     while(TI==0);
     TI=0;
	    SBUF='O';
     while(TI==0);
     TI=0;
	    SBUF='N';
     while(TI==0);
     TI=0;
	   }
	 while(RI==1);
 }
 else
 {
   SBUF='!';
   while(TI==0);
   TI=0;
   SBUF='N';
   while(TI==0);
   TI=0;
   SBUF='O';
   while(TI==0);
   TI=0;
   SBUF=' ';
   while(TI==0);
   TI=0;
   SBUF='V';
   while(TI==0);
   TI=0;
   SBUF='A';
   while(TI==0);
   TI=0;
   SBUF='L';
   while(TI==0);
   TI=0;
   SBUF='I';
   while(TI==0);
   TI=0;
   SBUF='D';
   while(TI==0);
   TI=0;
   SBUF=' ';
   while(TI==0);
   TI=0;
   SBUF='C';
   while(TI==0);
   TI=0;
   SBUF='O';
   while(TI==0);
   TI=0;
   SBUF='O';
   while(TI==0);
   TI=0;
   SBUF='R';
   while(TI==0);
   TI=0;
   SBUF='D';
   while(TI==0);
   TI=0;
   SBUF='I';
   while(TI==0);
   TI=0;
   SBUF='N';
   while(TI==0);
   TI=0;
   SBUF='A';
   while(TI==0);
   TI=0;
   SBUF='T';
   while(TI==0);
   TI=0;
   SBUF='E';
   while(TI==0);
   TI=0;
   SBUF='S';
   while(TI==0);
   TI=0;
   SBUF=' ';
   while(TI==0);
   TI=0;
   SBUF='A';
   while(TI==0);
   TI=0;
   SBUF='V';
   while(TI==0);
   TI=0;
   SBUF='A';
   while(TI==0);
   TI=0;
   SBUF='I';
   while(TI==0);
   TI=0;
   SBUF='L';
   while(TI==0);
   TI=0;
   SBUF='A';
   while(TI==0);
   TI=0;
   SBUF='B';
   while(TI==0);
   TI=0;
   SBUF='L';
   while(TI==0);
   TI=0;
   SBUF='E';
   while(TI==0);
   TI=0;
   SBUF='!';
   while(TI==0);
   TI=0;
   SBUF='\r';
   while(TI==0);
   TI=0;
   while(RI==1);
  }
  j=0;
  IE=0x90;
 }
 RI=0;
 while(RI==0);
}

void comma()
{
 unsigned int i,count=0;
 for(i=0;i<68;i++)
 {
   if(GPS[i]==',')
  {
    count++;
    if(count==2)
    m=i+1;
    if(count==3)
    k=i+1;
    if(count==5)
    l=i+1;
   }
 }
}

void latitude()
{
 unsigned int i;
 for(i=0;i<4;i++)
  LAT[i]=GPS[k+i];
 LAT[i]='\0';
}

void longitude()
{
 unsigned int i;
 for(i=0;i<7;i++)
  LONG[i]=GPS[l+i];
 LONG[i]='\0';
}

void main()
{
 TMOD=0X21;
 TH1=0XFD;
 SCON=0X50;
 TR1=1;
 SBUF='!';
 while(TI==0);
 TI=0;
 SBUF='B';
 while(TI==0);
 TI=0;
 SBUF='U';
 while(TI==0);
 TI=0;
 SBUF='S';
 while(TI==0);
 TI=0;
 SBUF=' ';
 while(TI==0);
 TI=0;
 SBUF='S';
 while(TI==0);
 TI=0;
 SBUF='T';
 while(TI==0);
 TI=0;
 SBUF='O';
 while(TI==0);
 TI=0;
 SBUF='P';
 while(TI==0);
 TI=0;
 SBUF=' ';
 while(TI==0);
 TI=0;
 SBUF='D';
 while(TI==0);
 TI=0;
 SBUF='I';
 while(TI==0);
 TI=0;
 SBUF='S';
 while(TI==0);
 TI=0;
 SBUF='P';
 while(TI==0);
 TI=0;
 SBUF='L';
 while(TI==0);
 TI=0;
 SBUF='A';
 while(TI==0);
 TI=0;
 SBUF='Y';
 while(TI==0);
 TI=0;
 SBUF='\r';
 while(TI==0);
 TI=0;
 delay(100);
 IE=0x90;
 a:goto a;
}
